export enum ErrorMessageCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INVALID_PARTNER_TYPE = 'INVALID_PARTNER_TYPE',
  PARTNER_NOT_FOUND = 'PARTNER_NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR'
}
